apiVersion: v1
kind: ConfigMap
metadata:
  name: conbench-config
  labels:
    app: conbench
data:
  CONBENCH_INTENDED_BASE_URL: "{{CONBENCH_INTENDED_BASE_URL}}"
  APPLICATION_NAME: "{{APPLICATION_NAME}}"
  BENCHMARKS_DATA_PUBLIC: "{{BENCHMARKS_DATA_PUBLIC}}"
  DB_NAME: "{{DB_NAME}}"
  DB_HOST: "{{DB_HOST}}"
  DB_PORT: "{{DB_PORT}}"
  FLASK_APP: "{{FLASK_APP}}"
  DISTRIBUTION_COMMITS: "{{DISTRIBUTION_COMMITS}}"
  SVS_TYPE: "{{SVS_TYPE}}"
