apiVersion: apps/v1
kind: Deployment
metadata:
  name: conbench-deployment
spec:
  selector:
    matchLabels:
      app: conbench
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: conbench
    spec:
      containers:
      - name: conbench
        image: "{{DOCKER_REGISTRY}}/{{FLASK_APP}}:{{BUILDKITE_COMMIT}}"
        command: [
          "gunicorn", "-b", "0.0.0.0:5000",
          "-w", "5",
          "-t", "120",
          "conbench:application",
          "--access-logfile=-",
          # Add L specifier to access log, to log request processing duration. Also see
          # https://github.com/conbench/conbench/issues/810
          "--access-logformat", '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" (%(L)s s)',
          "--error-logfile=-",
          "--preload"
          ]
        imagePullPolicy: "Always"
        ports:
          - name: gunicorn-port
            containerPort: 5000
        envFrom:
          - configMapRef:
              name: conbench-config
          - secretRef:
              name: conbench-secret
        resources:
          requests:
            memory: '2Gi'
            cpu: 0.5
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /api/ping/
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 20
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: "conbench-service"
  labels:
    app: conbench
  annotations:
    # "ip mode is required for sticky sessions to work with Application Load
    # Balancers"
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ports:
  - name: conbench-service-port
    port: 80
    # The port number above: the port that will be exposed by this service.
    # `targetPort` is documented with "Number or name of the port to access on
    # the pods targeted by the service."
    targetPort: gunicorn-port
    protocol: TCP
  type: NodePort
  selector:
    app: "conbench"
---
apiVersion: monitoring.coreos.com/v1
# This is a CRD defined by the prometheus-operator/kube-prometheus project
kind: ServiceMonitor
metadata:
  name: conbench-service-monitor
spec:
  selector:
    matchLabels:
      app: conbench
  endpoints:
    # It's important that ServiceMonitor i) refers to a Service port  and ii)
    # refers to it via its name.
    - port: conbench-service-port
      path: /metrics
      scheme: http
      # This defines the time resolution.
      interval: 30s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "conbench-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: {{CERTIFICATE_ARN}}
  labels:
    app: conbench-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: conbench-service
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
