services:
  schema:
    build:
      context: .
      dockerfile: Dockerfile.schema
    environment:
      APPLICATION_NAME: "conbench-schema"
      DB_USERNAME: "postgres"
      DB_HOST: "db"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      CREATE_ALL_TABLES: "false"
      CONBENCH_INTENDED_BASE_URL: "http://127.0.0.1:5000/"
      GITHUB_API_TOKEN: "${GITHUB_API_TOKEN:-}"
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: library/postgres:15.2-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1::5432"
