
version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "-b", "0.0.0.0:5000", "-w", "5", "conbench:application", "--access-logfile=-", "--error-logfile=-", "--preload"]
    volumes:
      - ${PWD}/_conbench-coverage-dir:/etc/conbench-coverage-dir
    depends_on:
      - dex
      - db
    environment:
      APPLICATION_NAME: "conbench-for-pytest"
      DB_USERNAME: "postgres"
      # From the docker-compose docs: "By default Compose sets up a single
      # network for your app. Each container for a service joins the default
      # network and is both reachable by other containers on that network, and
      # discoverable by them at a hostname identical to the container name."
      # That is why the DNS name `db` works.
      DB_HOST: "db"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      FLASK_APP: "conbench"
      FLASK_ENV: "development"
      FLASK_DEBUG: "true"
      REGISTRATION_KEY: "code"
      SECRET_KEY: "Person, woman, man, camera, TV"
      # Default log level is INFO, change to DEBUG as needed.
      # CONBENCH_LOG_LEVEL_STDERR: DEBUG
      OAUTHLIB_INSECURE_TRANSPORT: 1
      GOOGLE_CLIENT_ID: conbench-test-client
      GOOGLE_CLIENT_SECRET: AnotherStaticSecret
      CONBENCH_OIDC_ISSUER_URL: http://dex:5556/dex-for-conbench
      CONBENCH_INTENDED_BASE_URL: http://127.0.0.1:5000/

  dex:
    image: dexidp/dex:v2.35.3
    volumes:
      - ${PWD}/conbench/tests/containers/dex/config.yml:/etc/dex/config.docker.yaml
    ports:
      - "5556:5556"

  db:
    image: library/postgres:12.4
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["alembic", "upgrade", "head"]
    environment:
      APPLICATION_NAME: "conbench-for-pytest"
      CREATE_ALL_TABLES: "false"
      DB_USERNAME: "postgres"
      DB_HOST: "db"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      FLASK_APP: "conbench"
      FLASK_ENV: "development"
      REGISTRATION_KEY: "code"
      SECRET_KEY: "Person, woman, man, camera, TV"
      CONBENCH_INTENDED_BASE_URL: http://127.0.0.1:5000/
    depends_on:
      db:
        condition: service_healthy
