
version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "-b", "0.0.0.0:5000", "-w", "5", "conbench:application", "--access-logfile=-", "--error-logfile=-", "--preload"]
    volumes:
      - ${PWD}/_conbench-coverage-dir:/etc/conbench-coverage-dir
    environment:
      APPLICATION_NAME: "Conbench"
      DB_USERNAME: "postgres"
      # From the docker-compose docs: "By default Compose sets up a single
      # network for your app. Each container for a service joins the default
      # network and is both reachable by other containers on that network, and
      # discoverable by them at a hostname identical to the container name."
      # That is why the DNS name `db` works.
      DB_HOST: "db"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      FLASK_APP: "conbench"
      FLASK_ENV: "development"
      FLASK_DEBUG: "true"
      REGISTRATION_KEY: "code"
      SECRET_KEY: "Person, woman, man, camera, TV"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: library/postgres:12.4
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["alembic", "upgrade", "head"]
    environment:
      APPLICATION_NAME: "Conbench"
      CREATE_ALL_TABLES: "false"
      DB_USERNAME: "postgres"
      DB_HOST: "db"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      FLASK_APP: "conbench"
      FLASK_ENV: "development"
      REGISTRATION_KEY: "code"
      SECRET_KEY: "Person, woman, man, camera, TV"
    depends_on:
      db:
        condition: service_healthy
