apiVersion: v1
kind: ConfigMap
metadata:
  name: conbench-migration-config
  labels:
    app: conbench-migration
data:
  CREATE_ALL_TABLES: "false"
  DB_NAME: "{{DB_NAME}}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: conbench-migration
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: conbench-migration
        image: "{{DOCKER_REGISTRY}}/{{FLASK_APP}}:{{BUILDKITE_COMMIT}}"
        command:
        - /bin/sh
        - -c
        - sleep 30; alembic upgrade head;
        envFrom:
          - configMapRef:
              name: conbench-config
          - configMapRef:
              name: conbench-migration-config
          - secretRef:
              name: conbench-secret
      restartPolicy: Never
