steps:
  - label: "WIP"
    command:
      - cat conbench-secret.yml | sed "s/{{GOOGLE_CLIENT_ID}}/$(echo -n \"1059704187938-9ov5nsmq431amrdf1trcudhun3rech7m.apps.googleusercontent.com\" | base64)/g"
  - label: "WIP 2"
    command:
      - cat conbench-secret.yml | sed "s/{{GOOGLE_CLIENT_ID}}/$(echo -n 1059704187938\-9ov5nsmq431amrdf1trcudhun3rech7m\.apps\.googleusercontent\.com | base64)/g"

#
#  - label: "Build & Push"
#    key: "build-and-push"
#    concurrency: 1
#    concurrency_group: "conbench-staging-deploy"
#    command:
#      - set -x
#      - docker build -t ${FLASK_APP} .
#      - docker tag ${FLASK_APP}:latest ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}
#      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
#      - docker push ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}
#
#  - label: "Run Migrations"
#    key: "run-migrations"
#    depends_on: "build-and-push"
#    concurrency: 1
#    concurrency_group: "conbench-staging-deploy"
#    command:
#      - set -x
#      - aws eks --region us-east-2 update-kubeconfig --name ${EKS_CLUSTER}
#      - kubectl config set-context --current --namespace=staging
#      - cat migration-job.yml | sed "s/{{BUILDKITE_COMMIT}}/${BUILDKITE_COMMIT}/g; s/{{DB_NAME}}/${DB_NAME}/g; s/{{APPLICATION_NAME}}/${APPLICATION_NAME}/g; s/{{DB_HOST}}/${DB_HOST}/g; s/{{DB_PORT}}/${DB_PORT}/g; s/{{FLASK_APP}}/${FLASK_APP}/g; s/{{DOCKER_REGISTRY}}/${DOCKER_REGISTRY}/g; s/{{CERTIFICATE_ARN}}/${CERTIFICATE_ARN}/g; s/{{EKS_CLUSTER}}/${EKS_CLUSTER}/g; s/{{BENCHMARKS_DATA_PUBLIC}}/${BENCHMARKS_DATA_PUBLIC}/g" | kubectl delete --ignore-not-found=true -f -
#      - cat migration-job.yml | sed "s/{{BUILDKITE_COMMIT}}/${BUILDKITE_COMMIT}/g; s/{{DB_NAME}}/${DB_NAME}/g; s/{{APPLICATION_NAME}}/${APPLICATION_NAME}/g; s/{{DB_HOST}}/${DB_HOST}/g; s/{{DB_PORT}}/${DB_PORT}/g; s/{{FLASK_APP}}/${FLASK_APP}/g; s/{{DOCKER_REGISTRY}}/${DOCKER_REGISTRY}/g; s/{{CERTIFICATE_ARN}}/${CERTIFICATE_ARN}/g; s/{{EKS_CLUSTER}}/${EKS_CLUSTER}/g; s/{{BENCHMARKS_DATA_PUBLIC}}/${BENCHMARKS_DATA_PUBLIC}/g" | kubectl apply -f -
#      - kubectl wait --for=condition=complete --timeout=86400s job/conbench-migration
#      - (($(kubectl get job conbench-migration -o jsonpath={.status.succeeded}) == "1")) && exit 0 || exit 1
#
#  - label: "Deploy"
#    key: "deploy"
#    depends_on: "run-migrations"
#    concurrency: 1
#    concurrency_group: "conbench-staging-deploy"
#    command:
#      - set -x
#      - aws eks --region us-east-2 update-kubeconfig --name ${EKS_CLUSTER}
#      - kubectl config set-context --current --namespace=staging
#      - cat deploy.yml | sed "s/{{BUILDKITE_COMMIT}}/${BUILDKITE_COMMIT}/g; s/{{DB_NAME}}/${DB_NAME}/g; s/{{APPLICATION_NAME}}/${APPLICATION_NAME}/g; s/{{DB_HOST}}/${DB_HOST}/g; s/{{DB_PORT}}/${DB_PORT}/g; s/{{FLASK_APP}}/${FLASK_APP}/g; s/{{DOCKER_REGISTRY}}/${DOCKER_REGISTRY}/g; s/{{CERTIFICATE_ARN}}/${CERTIFICATE_ARN}/g; s/{{EKS_CLUSTER}}/${EKS_CLUSTER}/g; s/{{BENCHMARKS_DATA_PUBLIC}}/${BENCHMARKS_DATA_PUBLIC}/g" | kubectl apply -f -
#      - kubectl rollout status deployment/conbench-deployment
