steps:
  # TODO: use GitHub API to find if this commit had all CI checks passing.
  # Abort deployment if that is not the case. Also see
  # https://github.com/conbench/conbench/issues/319
  - label: "Build & Push"
    key: "build-and-push"
    concurrency: 1
    concurrency_group: "conbench-staging-deploy"
    command:
      - source .buildkite/utils.sh build_and_push

  - label: "Deploy secrets and config"
    key: "deploy-secrets-and-config"
    depends_on: "build-and-push"
    concurrency: 1
    concurrency_group: "conbench-staging-deploy"
    command:
      - source .buildkite/utils.sh deploy_secrets_and_config


  - label: "Run Migrations"
    key: "run-migrations"
    depends_on: "deploy-secrets-and-config"
    concurrency: 1
    concurrency_group: "conbench-staging-deploy"
    command:
      - source .buildkite/utils.sh run_migrations

  - label: "Deploy"
    key: "deploy"
    depends_on: "run-migrations"
    concurrency: 1
    concurrency_group: "conbench-staging-deploy"
    command:
      - source .buildkite/utils.sh deploy
