package main

import (
	"bytes"
	"context"
	"encoding/csv"
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"time"

	"github.com/conbench/conbench/sdk/go/conbench"
	"github.com/spf13/cobra"
)

type historyExportConfig struct {
	resultID string
	server   string
	token    string
	output   string
}

func parseHistoryExportArgs(args []string) (historyExportConfig, error) {
	var cfg historyExportConfig
	cmd := newHistoryExportCommand(io.Discard, func(_ context.Context, parsed historyExportConfig, _ io.Writer) error {
		cfg = parsed
		return nil
	})
	if err := executeParseCommand(cmd, args); err != nil {
		return historyExportConfig{}, err
	}
	return cfg, nil
}

func historyExportCommand(stdout io.Writer) *cobra.Command {
	return newHistoryExportCommand(stdout, runHistoryExportConfig)
}

func newHistoryExportCommand(
	stdout io.Writer,
	run func(context.Context, historyExportConfig, io.Writer) error,
) *cobra.Command {
	var cfg historyExportConfig
	cmd := configureCommand(&cobra.Command{
		Use:   "export <result-id>",
		Short: "Export benchmark history as CSV.",
		Args: func(cmd *cobra.Command, args []string) error {
			switch {
			case len(args) == 0:
				return commandUsageError(cmd, "missing benchmark result id")
			case len(args) > 1:
				return commandUsageError(cmd, "too many benchmark result ids")
			case cfg.server == "":
				return commandUsageError(cmd, "--server is required")
			}
			cfg.resultID = args[0]
			return nil
		},
		RunE: func(cmd *cobra.Command, _ []string) error {
			return run(cmd.Context(), cfg, stdout)
		},
	})
	cmd.Flags().StringVar(&cfg.server, "server", "", "Conbench server base URL (required)")
	cmd.Flags().StringVar(&cfg.token, "token", "", "bearer token for read authentication")
	cmd.Flags().StringVar(&cfg.output, "output", "", "write CSV to this file instead of stdout")
	return cmd
}

func runHistoryExportConfig(ctx context.Context, cfg historyExportConfig, stdout io.Writer) error {
	bearer, err := resolveBearer(cfg.token, cfg.server)
	if err != nil {
		return err
	}

	client, err := newClient(cfg.server)
	if err != nil {
		return err
	}
	resp, err := client.GetHistoryForResultWithResponse(ctx, cfg.resultID, bearerRequestEditor(bearer))
	if err != nil {
		return fmt.Errorf("get history from %s: %w", cfg.server, err)
	}
	if resp.JSON200 == nil {
		return statusError(resp.HTTPResponse, resp.Body)
	}

	out, err := renderHistoryCSV(cfg.resultID, resp.JSON200)
	if err != nil {
		return err
	}
	if cfg.output != "" {
		if err := os.WriteFile(cfg.output, out, 0o600); err != nil {
			return fmt.Errorf("write %s: %w", cfg.output, err)
		}
		return nil
	}
	_, err = stdout.Write(out)
	return err
}

func renderHistoryCSV(resultID string, series *conbench.HistorySeries) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# generated by conbench CLI")
	fmt.Fprintf(&buf, "# for result %s\n", resultID)
	fmt.Fprintf(&buf, "# history fingerprint: %s\n", series.HistoryFingerprint)

	writer := csv.NewWriter(&buf)
	if err := writer.Write([]string{
		"commit_time",
		"result_id",
		"commit_hash",
		"svs",
		"mean",
		"unit",
		"svs_type",
	}); err != nil {
		return nil, fmt.Errorf("write CSV header: %w", err)
	}

	samples := historySamples(series)
	sort.SliceStable(samples, func(i, j int) bool {
		left := samples[i]
		right := samples[j]
		switch {
		case left.CommitTimestamp == nil && right.CommitTimestamp == nil:
			return left.BenchmarkResultId < right.BenchmarkResultId
		case left.CommitTimestamp == nil:
			return false
		case right.CommitTimestamp == nil:
			return true
		case !left.CommitTimestamp.Equal(*right.CommitTimestamp):
			return left.CommitTimestamp.Before(*right.CommitTimestamp)
		default:
			return left.BenchmarkResultId < right.BenchmarkResultId
		}
	})

	for _, sample := range samples {
		if err := writer.Write([]string{
			formatHistoryTime(sample.CommitTimestamp),
			sample.BenchmarkResultId,
			sample.CommitHash,
			formatHistoryFloat(sample.SingleValueSummary),
			formatOptionalFloat(sample.Mean),
			formatOptionalString(sample.Unit),
			sample.SingleValueSummaryType,
		}); err != nil {
			return nil, fmt.Errorf("write CSV row: %w", err)
		}
	}
	writer.Flush()
	if err := writer.Error(); err != nil {
		return nil, fmt.Errorf("write CSV: %w", err)
	}
	return buf.Bytes(), nil
}

func historySamples(series *conbench.HistorySeries) []conbench.HistorySample {
	if series.Samples == nil {
		return nil
	}
	samples := make([]conbench.HistorySample, len(*series.Samples))
	copy(samples, *series.Samples)
	return samples
}

func formatHistoryTime(value *time.Time) string {
	if value == nil {
		return ""
	}
	return value.UTC().Format(time.RFC3339Nano)
}

func formatOptionalString(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

func formatOptionalFloat(value *float64) string {
	if value == nil {
		return ""
	}
	return formatHistoryFloat(*value)
}

func formatHistoryFloat(value float64) string {
	return strconv.FormatFloat(value, 'g', 8, 64)
}
