apiVersion: v1
kind: ConfigMap
metadata:
  name: conbench-migration-config
  labels:
    app: conbench-migration
data:
  CREATE_ALL_TABLES: "false"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: conbench-migration
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: conbench-migration
        image: "{{CONBENCH_WEBAPP_IMAGE_SPEC}}"
        command:
        - /bin/sh
        - -c
        - sleep 30; alembic upgrade head;
        envFrom:
          - configMapRef:
              name: conbench-config
          - configMapRef:
              name: conbench-migration-config
          - secretRef:
              name: conbench-secret
        resources:
          requests:
            # Pretend that we don't need resources, so that node placement
            # succeeds even on small-resource k8s clusters.
            memory: '1Mi'
            cpu: 1m
      restartPolicy: Never

