{
 "title": "Conbench / Web application overview",
 "tags": [ "conbench" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "timewindow", "label": "Time window width", "query": "1m, 2m, 5m" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Rate of exceptions thrown by request handlers [1/s], $timewindow mean",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_exceptions_total{namespace=\"$namespace\"}[$timewindow])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask response generation rate [1/s], $timewindow mean",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{namespace=\"$namespace\"}[$timewindow]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "GitHub HTTP API 403 error rate [1/s], $timewindow mean",
   "type": "timeseries",
   "description": "The rate of GitHub HTTP API responses received with status code 403",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(conbench_github_httpapi_403responses_total[$timewindow]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask response generation rate by status code [1/s], $timewindow mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total{namespace=\"$namespace\"}[$timewindow]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GitHub HTTP API request rate [1/s], $timewindow mean",
   "type": "timeseries",
   "description": "These are attempted HTTP request, i.e. this rate includes failed requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(conbench_github_httpapi_requests_total{namespace=\"$namespace\"}[$timewindow]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "non-GET requests: Flask HTTP response generation duration, event rate [1/s]. Observation period: $timewindow",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (le) (rate(flask_http_request_duration_seconds_bucket{namespace=\"$namespace\",method!=\"GET\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GitHub HTTP API quota left (x-ratelimit-remaining header value last seen)",
   "type": "timeseries",
   "description": "This is a gauge. Last update wins. -1 means: not seen an HTTP response yet carrying the x-ratelimit-remaining header. Each process reports this. Processes might die.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "conbench_github_httpapi_quota_remaining{namespace=\"$namespace\"}",
     "legendFormat": "pid:{{pid}}, {{instance}}"
    }
   ]
  },
  {
   "title": "/api GET requests: response generation duration, event rate [1/s]. Observation period: $timewindow",
   "type": "heatmap",
   "description": "This shows data only for those requests to /api/*\nRequests to /api/ping are excluded.\nRedirect responses are excluded.\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (le) (rate(flask_http_request_duration_seconds_bucket{namespace=\"$namespace\",method=\"GET\",path=~\"/api/.*\",path!~\"/api/ping.*\",status!~\"3..\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GitHub HTTP API request error rate [1/s], $timewindow mean",
   "type": "timeseries",
   "description": "The rate of failed HTTP requests, either after retrying or upon first attempt.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(conbench_github_httpapi_requests_failed_total{namespace=\"$namespace\"}[$timewindow]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}