#!/usr/bin/env bash
set -euo pipefail

# Generate internal/db/schema.sql from the Alembic migrations.
#
# Alembic is the temporary schema source of truth. See docs/site/operations.md
# and docs/site/storage-roadmap.md for the schema-ownership transition. This
# script runs the migrations against an ephemeral Postgres and dumps the
# resulting schema, which sqlc then consumes to generate typed Go.
#
# The migrations run inside a temporary schema image with Alembic, SQLAlchemy,
# requests, and pg_dump. It does not install the retired Flask application.
#
# Usage: scripts/gen_schema.sh [output-path]   (default: internal/db/schema.sql)

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="${1:-internal/db/schema.sql}"
PROJECT="conbench_schemagen"
COMPOSE=(docker compose -p "$PROJECT" -f docker-compose.schema.yml)
# Migrations do not call GitHub; default the token to empty to avoid warnings.
export GITHUB_API_TOKEN="${GITHUB_API_TOKEN:-}"

cleanup() { "${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true; }
trap cleanup EXIT

echo "[gen_schema] building schema image (provides alembic + pg_dump)…"
"${COMPOSE[@]}" build schema >/dev/null

echo "[gen_schema] starting ephemeral Postgres…"
"${COMPOSE[@]}" up -d db >/dev/null

echo "[gen_schema] waiting for Postgres to accept connections…"
for _ in $(seq 1 60); do
	if "${COMPOSE[@]}" exec -T db pg_isready -U postgres >/dev/null 2>&1; then
		break
	fi
	sleep 1
done

echo "[gen_schema] applying migrations (alembic upgrade head)…"
"${COMPOSE[@]}" run --rm --no-deps -e CREATE_ALL_TABLES=false schema alembic upgrade head

echo "[gen_schema] dumping schema → ${OUT}…"
mkdir -p "$(dirname "$OUT")"
{
	echo "-- Generated by scripts/gen_schema.sh from the Alembic migrations."
	echo "-- Source of truth: migrations/ (Alembic). Do not edit by hand."
	echo "-- Regenerate with: make schema"
	echo
	# Strip the volatile preamble (version banner, session SET/set_config, and
	# decorator comments) so the file is stable across pg_dump patch versions;
	# what remains is the DDL that sqlc parses. The trailing-blank-line strip
	# keeps the file in agreement with the end-of-file-fixer pre-commit hook,
	# so the generator output survives a commit unchanged.
	"${COMPOSE[@]}" exec -T db pg_dump \
		--schema-only --no-owner --no-privileges --no-comments \
		-U postgres postgres \
		| grep -vE '^--|^SET |^SELECT pg_catalog\.set_config' \
		| cat -s \
		| awk '{lines[NR]=$0} END {last=NR; while (last>0 && lines[last]=="") last--; for (i=1;i<=last;i++) print lines[i]}'
} >"$OUT"

echo "[gen_schema] wrote $(grep -c '' "$OUT") lines to ${OUT}"
